CREATE TABLE IF NOT EXISTS CATEGORIES
(   CTGR_ID          BIGINT       NOT NULL PRIMARY KEY
  , CTGR_NAME        VARCHAR(100) NOT NULL UNIQUE
  , CTGR_DESCRIPTION VARCHAR(100)
  , CTGR_VERSION     BIGINT       NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEMS
(   ITEM_ID      BIGINT        NOT NULL PRIMARY KEY
  , ITEM_CTGR_ID BIGINT        NOT NULL
  , ITEM_NAME    VARCHAR(100)  NOT NULL UNIQUE
  , ITEM_PRICE   NUMERIC(8, 2) NOT NULL
  , ITEM_VERSION BIGINT        NOT NULL
  , CONSTRAINT ITEM_CTGR_FK FOREIGN KEY (ITEM_CTGR_ID) REFERENCES CATEGORIES (CTGR_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS
(   CUST_ID       BIGINT       NOT NULL PRIMARY KEY
  , CUST_USERNAME VARCHAR(100) NOT NULL UNIQUE
  , CUST_VERSION  BIGINT       NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS
(   ORDR_ID BIGINT  NOT NULL PRIMARY KEY
  , ORDR_CUST_ID BIGINT  NOT NULL
  , ORDR_VERSION BIGINT  NOT NULL
  , CONSTRAINT ORDR_CUST_FK FOREIGN KEY (ORDR_CUST_ID) REFERENCES CUSTOMERS (CUST_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(   ORIT_ID  BIGINT  NOT NULL PRIMARY KEY
  , ORIT_ORDR_ID  BIGINT  NOT NULL
  , ORIT_ITEM_ID  BIGINT  NOT NULL
  , ORIT_QUANTITY INT     NOT NULL
  , ORIT_VERSION  BIGINT  NOT NULL
  , CONSTRAINT ORIT_ORDR_FK FOREIGN KEY (ORIT_ORDR_ID) REFERENCES ORDERS (ORDR_ID)
  , CONSTRAINT ORIT_ITEM_FK FOREIGN KEY (ORIT_ITEM_ID) REFERENCES ITEMS (ITEM_ID)
);

CREATE SEQUENCE IF NOT EXISTS ORDR_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS ORIT_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CUST_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS ITEM_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS CTGR_ID_SEQ;
